<a href="https://colab.research.google.com/github/rushdishams/learn-with-rushdi/blob/main/pandas/Pandas%20Interview%207%20-%20Create%20Dataframe%20with%20Null%20Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
import numpy as np

In [47]:
array = np.random.rand(5,2)

In [48]:
array

array([[0.01661138, 0.52249901],
       [0.31847777, 0.36215791],
       [0.78104389, 0.4365008 ],
       [0.27278756, 0.87778457],
       [0.36863953, 0.70176503]])

In [49]:
pd.DataFrame(array)

0         1
0  0.016611  0.522499
1  0.318478  0.362158
2  0.781044  0.436501
3  0.272788  0.877785
4  0.368640  0.701765

### Create a pandas dataframe with random null value

1. create a numpy array of random values
2. flatten the numpy array we created in step 1
3. in this flattened array, randomly select indices
4. impute the values in those indices with null values
5. create a pandas dataframe using the array

In [50]:
array

array([[0.01661138, 0.52249901],
       [0.31847777, 0.36215791],
       [0.78104389, 0.4365008 ],
       [0.27278756, 0.87778457],
       [0.36863953, 0.70176503]])

In [51]:
array.shape

(5, 2)

In [52]:
array.ravel()

array([0.01661138, 0.52249901, 0.31847777, 0.36215791, 0.78104389,
       0.4365008 , 0.27278756, 0.87778457, 0.36863953, 0.70176503])

In [53]:
array.ravel().shape

(10,)

In [54]:
array.ravel()[9]

0.7017650281644174

In [55]:
type(array.ravel())

numpy.ndarray

In [62]:
index = np.random.choice(array.size, 4, replace=False)

In [65]:
array.ravel()[index] = np.nan

In [66]:
array

array([[0.01661138,        nan],
       [0.31847777, 0.36215791],
       [       nan, 0.4365008 ],
       [       nan,        nan],
       [0.36863953, 0.70176503]])

In [67]:
pd.DataFrame(array)

0         1
0  0.016611       NaN
1  0.318478  0.362158
2       NaN  0.436501
3       NaN       NaN
4  0.368640  0.701765